# This file defines charm config options, and populates the Configure tab on Charmhub.
# If your charm does not require configuration options, delete this file entirely.
#
# See https://juju.is/docs/config for guidance.

options:
  contract_url:
    default: "https://contracts.canonical.com"
    description: URL of the Ubuntu Pro contracts service backend to use.
    type: string
  ppa:
    default: ""
    description: PPA from which to install the ubuntu-advantage-tools package.
    type: string
  token:
    default: ""
    description: Ubuntu Pro token obtained from https://ubuntu.com/pro.
    type: string
  override-http-proxy:
    default: ""
    description: http-proxy which can override juju http-proxy
    type: string
  override-https-proxy:
    default: ""
    description: https-proxy which can override juju https-proxy
    type: string
  override-ssl-cert-file:
    default: ""
    description: Path to a custom SSL certificate file to use for the Ubuntu Pro client actions.
    type: string
  livepatch_server_url:
    default: ""
    description: URL of the livepatch on-prem server. Unsetting will revert the on-prem server to the default server (https://livepatch.canonical.com).
    type: string
  livepatch_token:
    default: ""
    description:
      Authorization token for the livepatch on-prem server. Required if livepatch_server_url is set.
      Unsetting will revert the on-prem server to the default server (https://livepatch.canonical.com).
    type: string
  services:
    default: ""
    description:
      A comma-separated list of services to enable when attaching to a pro subscription. This list overrides the default services. If specified, only these services will be activated. If left empty, the default services are activated.
      A list of possible services can be found by running "pro status --all" on a machine with the ubuntu-pro-client package installed.
    type: string
