name: PR Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Linting
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install tox
        run: sudo apt-get update && sudo apt-get install -y tox
      
      - name: Run linting
        run: tox run -e lint

  unit-tests:
    runs-on: ubuntu-latest
    name: Unit Tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install tox
        run: sudo apt-get update && sudo apt-get install -y tox
      
      - name: Run unit tests
        run: tox run -e unit

  build:
    runs-on: ubuntu-latest
    name: Build Charms
    needs: [lint, unit-tests]
    strategy:
      matrix:
        build-target: [ubuntu-advantage, ubuntu-advantage_noble, ubuntu-pro, ubuntu-pro_noble]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup LXD
        uses: canonical/setup-lxd@v0.1.3
        with:
          channel: latest/stable

      - name: Install charmcraft
        run: sudo snap install charmcraft --classic
      
      - name: Build charm
        run: make ${{ matrix.build-target }}

  integration-tests:
    runs-on: ubuntu-latest
    name: Integration Tests
    needs: [build]
    strategy:
      matrix:
        build-target: [ubuntu-advantage, ubuntu-advantage_noble, ubuntu-pro, ubuntu-pro_noble]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup LXD
        uses: canonical/setup-lxd@v0.1.3
        with:
          channel: latest/stable

      - name: Install charmcraft
        run: sudo snap install charmcraft --classic
      
      - name: Install juju
        run: sudo snap install juju --channel 3/stable
      
      - name: Install tox
        run: sudo apt-get update && sudo apt-get install -y tox
      
      - name: Setup Juju
        run: |
          juju bootstrap localhost dev-controller
          
      - name: Run integration tests
        run: tox run -e integration
        env:
          PRO_CHARM_BUILD_TARGET: ${{ matrix.build-target }}
          PRO_CHARM_TEST_TOKEN: ${{ secrets.PRO_CHARM_TEST_TOKEN }}
          PRO_CHARM_TEST_LIVEPATCH_STAGING_TOKEN: ${{ secrets.PRO_CHARM_TEST_LIVEPATCH_STAGING_TOKEN }}
