name: PR Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    uses: ./.github/workflows/ci-tests.yml

  build:
    runs-on: ubuntu-latest
    name: Build Charms
    needs: [test]
    strategy:
      matrix:
        build-target: [ubuntu-pro, ubuntu-pro_noble]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup LXD
        uses: canonical/setup-lxd@v0.1.3
        with:
          channel: latest/stable

      - name: Install charmcraft
        run: sudo snap install charmcraft --classic
      
      - name: Build charm(s)
        run: make ${{ matrix.build-target }}